### PR TITLE
Remove deprecated class Nette\Object

### PR DESCRIPTION
**Pull request by trejjam**
This just remove `Nette\Object` and use `Nette\SmartObject` instead.

### CODE REVIEW

**Comment by hrach** [comment]
Great! Thanks!

**Comment by hrach** [comment]
Could you please update nette utils dependency to correct version that has the trait?

**Comment by trejjam** [comment]
Sure, I miss that. Updated

**Comment by hrach** [comment]
Great, thanks for the contribution!

**Pull request merged**
